### ISSUE TITLE
Prepare for PHPStan 2.0

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/wp-compat#11]
Resources:

* https://github.com/phpstan/phpstan/discussions/11816
* https://github.com/phpstan/phpstan-src/blob/2.0.x/changelog-2.0.md
* https://github.com/phpstan/phpstan-src/blob/2.0.x/UPGRADING.md

Some prior art:

* https://github.com/swissspidy/phpstan-no-private/pull/20
* https://github.com/szepeviktor/phpstan-wordpress/pull/243

**Comment by johnbillion** [comment]
Thanks, I'll find some time to take a look

**Comment by swissspidy** [comment]
PHPStan 2.0 is now released: https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants

**Comment by johnbillion** [comment]
Fixed in #16.
